// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: location.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one
insert into
  location (name, longitude, latitude)
values
  (
    $1,
    $2,
    $3
  )
returning
  id, name, longitude, latitude, created_at, deleted_at
`

type CreateLocationParams struct {
	Name      string
	Longitude float64
	Latitude  float64
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation, arg.Name, arg.Longitude, arg.Latitude)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Longitude,
		&i.Latitude,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
update location
set
  deleted_at = now()
where
  id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const selectLocationById = `-- name: SelectLocationById :one
select
  id, name, longitude, latitude, created_at, deleted_at
from
  location
where
  id = $1
  and deleted_at is null
`

func (q *Queries) SelectLocationById(ctx context.Context, id int32) (Location, error) {
	row := q.db.QueryRow(ctx, selectLocationById, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Longitude,
		&i.Latitude,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectLocations = `-- name: SelectLocations :many
select
  id, name, longitude, latitude, created_at, deleted_at
from
  location
where
  deleted_at is null
order by
  created_at desc
`

func (q *Queries) SelectLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, selectLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Longitude,
			&i.Latitude,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLocationsByDistance = `-- name: SelectLocationsByDistance :many
select
  id,
  name,
  longitude,
  latitude,
  created_at,
  deleted_at,
  SQRT(
    POW (longitude - $1, 2) + POW (latitude - $2, 2)
  ) as distance
from
  location
where
  deleted_at is null
order by
  distance asc
`

type SelectLocationsByDistanceParams struct {
	Longitude float64
	Latitude  float64
}

type SelectLocationsByDistanceRow struct {
	ID        int32
	Name      string
	Longitude float64
	Latitude  float64
	CreatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
	Distance  float64
}

func (q *Queries) SelectLocationsByDistance(ctx context.Context, arg SelectLocationsByDistanceParams) ([]SelectLocationsByDistanceRow, error) {
	rows, err := q.db.Query(ctx, selectLocationsByDistance, arg.Longitude, arg.Latitude)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectLocationsByDistanceRow
	for rows.Next() {
		var i SelectLocationsByDistanceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Longitude,
			&i.Latitude,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
