// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: location.sql

package database

import (
	"context"
)

const selectLocationById = `-- name: SelectLocationById :one
select
  id, name, street_address, apartment, city, state, zip, country, created_at, deleted_at
from
  location
where
  id = $1
  and deleted_at is null
`

func (q *Queries) SelectLocationById(ctx context.Context, id int32) (Location, error) {
	row := q.db.QueryRow(ctx, selectLocationById, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StreetAddress,
		&i.Apartment,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Country,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectLocations = `-- name: SelectLocations :many
select
  id, name, street_address, apartment, city, state, zip, country, created_at, deleted_at
from
  location
where
  deleted_at is null
limit
  $2
offset
  $1
`

type SelectLocationsParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) SelectLocations(ctx context.Context, arg SelectLocationsParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, selectLocations, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StreetAddress,
			&i.Apartment,
			&i.City,
			&i.State,
			&i.Zip,
			&i.Country,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
