// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Location struct {
	ID            int32
	Name          string
	StreetAddress string
	Apartment     pgtype.Text
	City          string
	State         string
	Zip           string
	Country       string
	CreatedAt     pgtype.Timestamp
	DeletedAt     pgtype.Timestamp
}

type Review struct {
	ID          int32
	UserID      int32
	LocationID  int32
	Title       pgtype.Text
	Description pgtype.Text
	Rating      int32
	CreatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type Session struct {
	ID           int32
	UserID       int32
	RefreshToken string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
}

type User struct {
	ID        int32
	Username  string
	Password  string
	CreatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}
