// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
insert into
  review (user_id, location_id, title, description, rating)
values
  (
    $1,
    $2,
    $3,
    $4,
    $5
  )
returning
  id, user_id, location_id, title, description, rating, created_at, deleted_at
`

type CreateReviewParams struct {
	UserID      int32
	LocationID  int32
	Title       pgtype.Text
	Description pgtype.Text
	Rating      int32
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.UserID,
		arg.LocationID,
		arg.Title,
		arg.Description,
		arg.Rating,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LocationID,
		&i.Title,
		&i.Description,
		&i.Rating,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
update review
set
  deleted_at = now()
where
  id = $1
  and deleted_at is null
`

func (q *Queries) DeleteReview(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const selectReview = `-- name: SelectReview :one
select
  id, user_id, location_id, title, description, rating, created_at, deleted_at
from
  review
where
  id = $1
  and deleted_at is null
`

func (q *Queries) SelectReview(ctx context.Context, id int32) (Review, error) {
	row := q.db.QueryRow(ctx, selectReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LocationID,
		&i.Title,
		&i.Description,
		&i.Rating,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectReviews = `-- name: SelectReviews :many
select
  id, user_id, location_id, title, description, rating, created_at, deleted_at
from
  review
where
  deleted_at is null
order by
  created_at desc
`

func (q *Queries) SelectReviews(ctx context.Context) ([]Review, error) {
	rows, err := q.db.Query(ctx, selectReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LocationID,
			&i.Title,
			&i.Description,
			&i.Rating,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectReviewsByLocation = `-- name: SelectReviewsByLocation :many
select
  id, user_id, location_id, title, description, rating, created_at, deleted_at
from
  review
where
  location_id = $1
  and deleted_at is null
order by
  created_at desc
`

func (q *Queries) SelectReviewsByLocation(ctx context.Context, locationID int32) ([]Review, error) {
	rows, err := q.db.Query(ctx, selectReviewsByLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LocationID,
			&i.Title,
			&i.Description,
			&i.Rating,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectReviewsByUser = `-- name: SelectReviewsByUser :many
select
  id, user_id, location_id, title, description, rating, created_at, deleted_at
from
  review
where
  user_id = $1
  and deleted_at is null
order by
  created_at desc
`

func (q *Queries) SelectReviewsByUser(ctx context.Context, userID int32) ([]Review, error) {
	rows, err := q.db.Query(ctx, selectReviewsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LocationID,
			&i.Title,
			&i.Description,
			&i.Rating,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :one
update review
set
  title = $1,
  description = $2,
  rating = $3
where
  id = $4
  and deleted_at is null
returning
  id, user_id, location_id, title, description, rating, created_at, deleted_at
`

type UpdateReviewParams struct {
	Title       pgtype.Text
	Description pgtype.Text
	Rating      int32
	ID          int32
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReview,
		arg.Title,
		arg.Description,
		arg.Rating,
		arg.ID,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LocationID,
		&i.Title,
		&i.Description,
		&i.Rating,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
