// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
insert into
  session (user_id, refresh_token, deleted_at)
values
  (
    $1,
    $2,
    $3
  )
returning
  id, user_id, refresh_token, created_at, updated_at, deleted_at
`

type CreateSessionParams struct {
	UserID       int32
	RefreshToken string
	DeletedAt    pgtype.Timestamp
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.RefreshToken, arg.DeletedAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
update session
set
  deleted_at = now()
where
  id = $1
  and deleted_at > now()
`

func (q *Queries) DeleteSession(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const updateSession = `-- name: UpdateSession :one
update session
set
  refresh_token = $1,
  updated_at = now()
where
  id = $2
  and deleted_at > now()
returning
  id, user_id, refresh_token, created_at, updated_at, deleted_at
`

type UpdateSessionParams struct {
	RefreshToken string
	ID           int32
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSession, arg.RefreshToken, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
