// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into
  "user" (username, password)
values
  ($1, $2)
returning
  id, username, password, created_at, deleted_at
`

type CreateUserParams struct {
	Username string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
update "user"
set
  deleted_at = now()
where
  id = $1
  and deleted_at is null
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const selectSessionById = `-- name: SelectSessionById :one
select
  id, user_id, refresh_token, created_at, updated_at, deleted_at
from
  session
where
  id = $1
  and deleted_at > now()
`

func (q *Queries) SelectSessionById(ctx context.Context, id int32) (Session, error) {
	row := q.db.QueryRow(ctx, selectSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectUserById = `-- name: SelectUserById :one
select
  id, username, password, created_at, deleted_at
from
  "user"
where
  id = $1
  and deleted_at is null
`

func (q *Queries) SelectUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, selectUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectUserByUsername = `-- name: SelectUserByUsername :one
select
  id, username, password, created_at, deleted_at
from
  "user"
where
  username = $1
  and deleted_at is null
`

func (q *Queries) SelectUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, selectUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
update "user"
set
  password = $1
where
  id = $2
  and deleted_at is null
returning
  id, username, password, created_at, deleted_at
`

type UpdateUserParams struct {
	Password string
	ID       int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Password, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
